name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oprypin/install-crystal@v1
        with:
          crystal: 0.36.1
      - run: shards install
      - run: crystal docs --project-name "Likee Scrapepr" --canonical-base-url "https://absolab.xyz/likee-scraper"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
